// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCthlCcKBQ5-BCtxRgZuwAG59Wa1JRP2to',
    appId: '1:236692996308:web:3b3ca44a76cc3624eb3b41',
    messagingSenderId: '236692996308',
    projectId: 'mangxahoi-4437b',
    authDomain: 'mangxahoi-4437b.firebaseapp.com',
    storageBucket: 'mangxahoi-4437b.firebasestorage.app',
    measurementId: 'G-ZETHPJM7X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy0bUJrk3VA7ysLIDbo0FMGhY-OAatBBY',
    appId: '1:236692996308:android:3df3958ed100b2fceb3b41',
    messagingSenderId: '236692996308',
    projectId: 'mangxahoi-4437b',
    storageBucket: 'mangxahoi-4437b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCthlCcKBQ5-BCtxRgZuwAG59Wa1JRP2to',
    appId: '1:236692996308:web:412ac5c24320d37eeb3b41',
    messagingSenderId: '236692996308',
    projectId: 'mangxahoi-4437b',
    authDomain: 'mangxahoi-4437b.firebaseapp.com',
    storageBucket: 'mangxahoi-4437b.firebasestorage.app',
    measurementId: 'G-3QB08D3MX9',
  );

}